#!/bin/bash

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]; then
    cd $OPENSHIFT_DATA_DIR
    mkdir m2/repository
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]; then
    cd $OPENSHIFT_DATA_DIR
    mkdir logs
fi

cd $OPENSHIFT_REPO_DIR
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

mvn -s .openshift/config/settings.xml clean -Popenshift clean install