#!/bin/bash

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]; then
    cd $OPENSHIFT_DATA_DIR
    mkdir m2/repository
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]; then
    cd $OPENSHIFT_DATA_DIR
    mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.9 ]; then
    cd $OPENSHIFT_DATA_DIR
    wget http://apache.hippo.nl/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    tar -zxf *.tar.gz
    rm -rf *.tar.gz
fi

cd $OPENSHIFT_REPO_DIR
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.9/bin
export MAVEN_OPTS="-Xms384m -Xmx412m"

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$M2:$PATH

mvn -s .openshift/config/settings.xml clean -Popenshift clean install
cp src/Starter/target/*.war $OPENSHIFT_DATA_DIR/webapps/ROOT.war