#%RAML 1.0 Library
types:
  Coordinate: !include ../types/Coordinate.raml
  Entity: !include ../types/Entity.raml
  Dashboard: !include ../types/Dashboard.raml
  User: !include ../types/User.raml
  Category: !include ../types/Category.raml
  Request: !include ../types/Request.raml
  Offer: !include ../types/Offer.raml
  Conversation: !include ../types/Conversation.raml
  Message: !include ../types/Message.raml
